In [77]:
function OtsuMethod(Data)
    #Pa que esto funcione hay que mandar los datos ya sin NaNs u otras mugres
    minimo=minimum(Data)
    maximo=maximum(Data)
    binsdefault=2*ceil(Int,sqrt(length(Data)))
    (rango, cuentas)=hist(Data,binsdefault)
    tantos=length(rango)
    valores
    omega1=0
    omega2=0
    mu1=0
    mu2=0
    sigmab=0
    sigmabtemp=0
    tbest=0
    varlim=0
    for t=1:tantos-1
        omega1=sum(cuentas[1:t])
        omega2=sum(cuentas[t+1:tantos-1])
        mu1=sum(cuentas[1:t].*rango[1:t])/omega1
        mu2=sum(cuentas[t+1:tantos-1].*rango[t+1:tantos-1])/omega2        
        sigmabtemp=omega1*omega2*((mu1-mu2)^2)
        if sigmabtemp>sigmab
            sigmab=sigmabtemp
            tbest=t
            varlim=rango[t]
        end
    end
    return (sigmab,tbest,varlim)
end

OtsuMethod (generic function with 1 method)

In [65]:
DatosPrueba1=readdlm("DesviacionesTotalesEjemplo01.dat");

In [66]:
DatosPrueba1=reshape(DatosPrueba1,size(DatosPrueba1)[1]*size(DatosPrueba1)[2]);


In [73]:
map!(x->abs(x)>60? 0.0:x, DatosPrueba);

In [67]:
DatosPrueba1

4096-element Array{Float64,1}:
 63.5519
 15.2189
 15.1487
 15.225 
 15.1806
 15.863 
 15.3221
 15.3783
 14.5119
 15.8327
 15.5044
 14.7791
 16.6736
  ⋮     
 16.5654
 16.1853
 14.1098
 15.2896
 16.1733
 14.2743
 17.5464
 14.0111
 15.0867
 13.9587
 15.2409
 14.5564

4096-element Array{Float64,1}:
  0.0   
 15.2189
 15.1487
 15.225 
 15.1806
 15.863 
 15.3221
 15.3783
 14.5119
 15.8327
 15.5044
 14.7791
 16.6736
  ⋮     
 16.5654
 16.1853
 14.1098
 15.2896
 16.1733
 14.2743
 17.5464
 14.0111
 15.0867
 13.9587
 15.2409
 14.5564

In [78]:
OtsuMethod(DatosPrueba)

(2.265979747893028e7,35,16.5)

In [19]:
length(0.0:50:1650)

34

In [37]:
[0.9, 7, 23, 12.1, 0.1, 98].*[(0.0:50:1650)[23:28]]

6-element Array{Float64,1}:
    990.0
   8050.0
  27600.0
  15125.0
    130.0
 132300.0