Por alguna razón, si leemos (read) dos veces el archivo (arx) abierto, la segunda vez nos da un array vacio. 
Asi que mas bien lo leemos y lo cerramos de una.

In [34]:
arx=open("../ABFiles/Eduardo/C1C31000.DAT", "r")
databin=read(arx)
close(arx)

In [35]:
typeof(databin) # Los datos estan en bytes separados en palabras de 8 bytes.

Array{UInt8,1}

In [36]:
head=databin[1:4]

4-element Array{UInt8,1}:
 0x41
 0x42
 0x46
 0x20

In [29]:
string(head[4]), string(50, base=7), Char(head[4])

("50", "101", '2')

Lo que descubrió swharden es que el 4 número nos dice si es un abf1 o un abf2. Si el número es un espacio (en ASCII es el número 32) es un abf1. Si es un 50 (ASCII para "2") es un abf2:
 - ascii 32 es espacio -> abf1
 - ascii 50 es 2 -> abf2

In [10]:
convert(Int,databin[4]) #aquí vemos que tipo de archivo es. Curiosamente 0x32 es 50, no 32. ( 3 * 16 +2 )

50

In [38]:
map(Char, head) # and here it is

4-element Array{Char,1}:
 'A'
 'B'
 'F'
 ' '

In [37]:
if( Char(head[4])=='2')
    println( "Tenemos un archivo abf2")
elseif ( Char(head[4])==' ')
    println( "Tenemos un archivo abf1")
else
    println( "no tengo zorra idea de que es esto")
end

Tenemos un archivo abf1


In [16]:
aver=databin[13:16]

4-element Array{UInt8,1}:
 0x01
 0x00
 0x00
 0x00

In [49]:
averviendo=IOBuffer(aver)
read(averviendo, Int32)

1

In [52]:
averviendo=IOBuffer(head)
encabezado=read(averviendo, String)

"ABF "

In [53]:
typeof(encabezado)

String

In [27]:
?Char

search: Char ischardev Cchar skipchars Cuchar Cwchar_t AbstractChar



```
Char(c::Union{Number,AbstractChar})
```

`Char` is a 32-bit [`AbstractChar`](@ref) type that is the default representation of characters in Julia.  `Char` is the type used for character literals like `'x'` and it is also the element type of [`String`](@ref).

In order to losslessly represent arbitrary byte streams stored in a `String`, a `Char` value may store information that cannot be converted to a Unicode codepoint — converting such a `Char` to `UInt32` will throw an error. The [`isvalid(c::Char)`](@ref) function can be used to query whether `c` represents a valid Unicode character.


In [13]:
?parse

search: parse tryparse partialsortperm partialsortperm! pairs skipchars



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```
