In [1]:
putinsky=randn(64,64)

64x64 Array{Float64,2}:
  2.57881     0.55527    -0.266723    …   0.951093   0.234025   0.398693 
  1.4471     -0.306577   -0.651351       -1.18463    2.41992    0.707307 
 -0.11636     1.0557      0.126061       -1.75001    0.267217   0.367646 
  0.779727    0.479685    0.635946        0.377984   0.44677    0.229074 
 -0.143341   -0.0980095   0.247104        0.420635   0.369644   1.01059  
  0.425593    0.898718    0.229276    …   0.811675  -1.45152   -0.964506 
  0.750009   -0.0168874  -0.405737        0.067852  -1.1139    -1.84118  
 -0.0471936  -0.499141   -0.516288        1.26516   -1.47737    1.53999  
 -2.07652    -1.05243     0.421015        0.943506  -0.953385   0.563925 
 -0.475821    0.292034    1.3126         -0.433702  -1.23742    0.224894 
  0.317001   -0.667828    0.597207    …  -0.141556   1.09937    0.100679 
  1.42064    -1.14748    -0.760922        1.56652   -0.169461   1.7735   
 -0.903888   -0.0150664   1.16305        -0.529777   0.25375    2.43035  
  ⋮           

In [7]:
map!(x->floor(x), putinsky)

64x64 Array{Float64,2}:
  2.0   0.0  -1.0   1.0  -2.0   0.0  …   0.0   0.0  -1.0   0.0   0.0   0.0
  1.0  -1.0  -1.0   1.0  -2.0   1.0      1.0  -1.0   1.0  -2.0   2.0   0.0
 -1.0   1.0   0.0  -1.0   1.0   0.0     -1.0   0.0  -2.0  -2.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   0.0      0.0   0.0  -1.0   0.0   0.0   0.0
 -1.0  -1.0   0.0   0.0  -1.0  -1.0      0.0  -2.0  -2.0   0.0   0.0   1.0
  0.0   0.0   0.0  -1.0   0.0  -1.0  …   1.0   1.0  -1.0   0.0  -2.0  -1.0
  0.0  -1.0  -1.0   1.0  -1.0  -1.0      0.0   0.0   0.0   0.0  -2.0  -2.0
 -1.0  -1.0  -1.0   2.0   0.0  -1.0     -1.0  -2.0  -2.0   1.0  -2.0   1.0
 -3.0  -2.0   0.0   1.0   0.0  -1.0     -1.0   2.0   0.0   0.0  -1.0   0.0
 -1.0   0.0   1.0   1.0  -1.0  -4.0      0.0  -2.0  -2.0  -1.0  -2.0   0.0
  0.0  -1.0   0.0   0.0   1.0  -1.0  …  -1.0   1.0   0.0  -1.0   1.0   0.0
  1.0  -2.0  -1.0   0.0  -1.0  -1.0     -1.0  -1.0  -1.0   1.0  -1.0   1.0
 -1.0  -1.0   1.0   0.0  -1.0  -1.0      0.0   1.0  -1.0  -1.0   0.0   2.0
 

In [10]:
putete=map(x->convert(Int16, x), putinsky)

64x64 Array{Int16,2}:
  2   0  -1   1  -2   0  -1  -1   0  …  -2  -1   0   0   0  -1   0   0   0
  1  -1  -1   1  -2   1   0  -1  -1      0   1   0   1  -1   1  -2   2   0
 -1   1   0  -1   1   0   1   0  -1      1   1   0  -1   0  -2  -2   0   0
  0   0   0   0  -1   0  -1  -1   0      0  -1  -1   0   0  -1   0   0   0
 -1  -1   0   0  -1  -1  -2   0  -3      1  -1   0   0  -2  -2   0   0   1
  0   0   0  -1   0  -1  -1  -1  -3  …   2  -2   0   1   1  -1   0  -2  -1
  0  -1  -1   1  -1  -1   0   1   0     -1   2  -1   0   0   0   0  -2  -2
 -1  -1  -1   2   0  -1   0   0  -1     -1   0   1  -1  -2  -2   1  -2   1
 -3  -2   0   1   0  -1  -1  -1   0      1   0   0  -1   2   0   0  -1   0
 -1   0   1   1  -1  -4  -1  -1  -1     -1   0   0   0  -2  -2  -1  -2   0
  0  -1   0   0   1  -1  -2  -2  -2  …   1  -3   0  -1   1   0  -1   1   0
  1  -2  -1   0  -1  -1   0  -1  -1     -1  -1  -2  -1  -1  -1   1  -1   1
 -1  -1   1   0  -1  -1  -1  -1  -2     -1  -2  -2   0   1  -1  -1   0   2
  ⋮

In [20]:
ActividadNegativa=Array{Int16,2}
ActividadPositiva=Array{Int16,2}
SpikeCountPositivo=zeros(64,64);
SpikeCountNegativo=zeros(64,64);
SpikeCountTotal=zeros(64,64;)
for j=1:64, k=1:64          
    if(putete[j,k]<-0.0)      
        ActividadNegativa=vcat(ActividadNegativa, [j k])
        SpikeCountNegativo[j,k]+=1
    elseif(putete[j,k]>0.0) 
        ActividadPositiva=vcat(ActividadPositiva, [j, k])
        SpikeCountPositivo[j,k]+=1
    end
end

LoadError: mismatch in dimension 2
while loading In[20], in expression starting on line 6

In [18]:
ActividadNegativa

3987-element Array{Any,1}:
   Array{Int16,2}
  1              
  3              
  1              
  5              
  1              
  7              
  1              
  8              
  1              
 11              
  1              
 13              
  ⋮              
 64              
 55              
 64              
 58              
 64              
 59              
 64              
 61              
 64              
 62              
 64              
 63              