# CSD y CM para actividad evocada

In [2]:
using HDF5

In [3]:
DatosPrueba=h5open("/media/bodega/050815-hdf5/050815_1R0.brw", "r")

HDF5 data file: /media/bodega/050815-hdf5/050815_1R0.brw

In [4]:
Apunta=DatosPrueba["3BData/Raw"]

HDF5 dataset: /3BData/Raw (file: /media/bodega/050815-hdf5/050815_1R0.brw)

In [7]:
Blabla=read(Apunta);
Blaejemplo=reshape(Blabla[:,5000], 64,64)

64x64 Array{Uint16,2}:
 0x0000  0x0806  0x07f6  0x0800  0x0800  …  0x0803  0x0801  0x07f4  0x07f9
 0x07fe  0x0804  0x07f5  0x07f1  0x07f9     0x0808  0x0803  0x07ee  0x07fc
 0x07fa  0x0804  0x080c  0x07f6  0x07f1     0x0809  0x07e7  0x07fb  0x07ff
 0x07ff  0x0813  0x07fc  0x0806  0x07f9     0x0801  0x07fd  0x0800  0x07fd
 0x07fe  0x07fc  0x07fa  0x07f2  0x07f1     0x0806  0x0801  0x07f2  0x0806
 0x07f3  0x0803  0x0807  0x0801  0x0803  …  0x0800  0x07f2  0x0800  0x07fb
 0x0802  0x0809  0x07f4  0x07f8  0x07f5     0x080d  0x07f8  0x07fa  0x0802
 0x080c  0x0810  0x0805  0x0803  0x0800     0x080d  0x07f1  0x0000  0x0000
 0x0808  0x0806  0x07fe  0x07f6  0x07f8     0x0801  0x07e9  0x07f4  0x0806
 0x07f3  0x080d  0x07ff  0x0000  0x0808     0x0805  0x07ed  0x07fc  0x07f9
 0x07f5  0x080a  0x0809  0x07f4  0x07f3  …  0x07fd  0x07ee  0x0805  0x0810
 0x07f4  0x0802  0x0808  0x0803  0x07f2     0x0800  0x07f4  0x07f1  0x07fd
 0x0800  0x0800  0x0812  0x07f7  0x07fb     0x0808  0x07f4  0x07ff  0x0806
  

In [8]:
writedlm("Blaejemplo.dat", Blaejemplo)

In [17]:
Blaejemplo2=int16(Blaejemplo);


In [21]:
Blaejemplo*(-1)+2000

64x64 Array{Uint16,2}:
 0x07d0  0xffca  0xffda  0xffd0  0xffd0  …  0xffcd  0xffcf  0xffdc  0xffd7
 0xffd2  0xffcc  0xffdb  0xffdf  0xffd7     0xffc8  0xffcd  0xffe2  0xffd4
 0xffd6  0xffcc  0xffc4  0xffda  0xffdf     0xffc7  0xffe9  0xffd5  0xffd1
 0xffd1  0xffbd  0xffd4  0xffca  0xffd7     0xffcf  0xffd3  0xffd0  0xffd3
 0xffd2  0xffd4  0xffd6  0xffde  0xffdf     0xffca  0xffcf  0xffde  0xffca
 0xffdd  0xffcd  0xffc9  0xffcf  0xffcd  …  0xffd0  0xffde  0xffd0  0xffd5
 0xffce  0xffc7  0xffdc  0xffd8  0xffdb     0xffc3  0xffd8  0xffd6  0xffce
 0xffc4  0xffc0  0xffcb  0xffcd  0xffd0     0xffc3  0xffdf  0x07d0  0x07d0
 0xffc8  0xffca  0xffd2  0xffda  0xffd8     0xffcf  0xffe7  0xffdc  0xffca
 0xffdd  0xffc3  0xffd1  0x07d0  0xffc8     0xffcb  0xffe3  0xffd4  0xffd7
 0xffdb  0xffc6  0xffc7  0xffdc  0xffdd  …  0xffd3  0xffe2  0xffcb  0xffc0
 0xffdc  0xffce  0xffc8  0xffcd  0xffde     0xffd0  0xffdc  0xffdf  0xffd3
 0xffd0  0xffd0  0xffbe  0xffd9  0xffd5     0xffc8  0xffdc  0xffd1  0xffca
  

In [7]:
include("../BrainWaveSoft/ConvertidorDigitalAnalogo.jl")

#=
capacidad=400000

function ConvierteAMiliVolts(archivo::HDF5File)
    ApuntaFactores=archivo["/3BRecInfo/3BRecVars"]
    Factores=read(ApuntaFactores)
    Frames=Factores["NRecFrames"][1]
    if Frames > capacidad
        println("Error: No puedo cargar todos los datos de un jalon")
        return 0;
    else
        ApuntaDatos=archivo["/3BData/Raw"]
        Aux=float(read(ApuntaDatos))
        #Aux=read(ApuntaDatos)       
        Signo=float(Factores["SignalInversion"][1])
        Divisor=float(2^Factores["BitDepth"][1])
        FactorConversion=(Factores["MaxVolt"][1]-Factores["MinVolt"][1])/(Divisor)*Signo
        Offset=float(Factores["MinVolt"][1])*Signo
        #println("Factor: ", FactorConversion, " Offset: ", Offset, "Signo: ", Signo)
        #Aux2=similar(Aux)
        Aux2=FactorConversion*Aux+Offset
        #Aux=0
        
    return Aux2
    end
end
=#


In [8]:
@time hola=ConvertidorDigitalAnalogo.ConvierteAMiliVolts(DatosPrueba);

elapsed time: 8.872630196 seconds (22432224584 bytes allocated, 6.45% gc time)


4096x210624 Array{Float64,2}:
 4125.0      4125.0      4125.0      …  4125.0      4125.0      4125.0    
  -16.1133    -74.5239      2.01416      -38.269     -32.2266     32.2266 
   -2.01416   -70.4956    -38.269         -4.02832    12.085      28.1982 
   -4.02832   -96.6797    -18.1274       -22.1558      0.0        38.269  
    2.01416  -106.75       -6.04248      -26.1841      0.0        34.2407 
  -54.3823   -100.708      -6.04248  …   -28.1982    -10.0708     14.0991 
  -42.2974    -80.5664    -34.2407       -32.2266    -22.1558     34.2407 
  -16.1133    -78.5522    -10.0708       -16.1133      4.02832    20.1416 
  -14.0991    -84.5947     -6.04248      -16.1133     -8.05664    16.1133 
  -66.4673   -112.793      -2.01416       -2.01416   -18.1274      4.02832
  -22.1558    -94.6655     -8.05664  …   -40.2832    -16.1133     18.1274 
  -32.2266    -90.6372      0.0          -14.0991     -4.02832    18.1274 
  -32.2266   -106.75      -12.085        -22.1558     16.1133     16.1

In [9]:
reshape(hola,64,64,210624)

64x64x210624 Array{Float64,3}:
[:, :, 1] =
 4125.0        4.02832  -14.0991  …  -38.269     -44.3115   -60.4248 
  -16.1133    30.2124   -40.2832       6.04248   -46.3257   -30.2124 
   -2.01416   12.085    -50.354      -10.0708    -32.2266   -16.1133 
   -4.02832    6.04248  -34.2407     -28.1982    -74.5239   -22.1558 
    2.01416   26.1841   -30.2124      -6.04248   -52.3682   -40.2832 
  -54.3823    -8.05664  -34.2407  …  -38.269     -52.3682   -60.4248 
  -42.2974    22.1558   -44.3115     -20.1416    -30.2124   -42.2974 
  -16.1133    14.0991   -28.1982     -14.0991   4125.0     4125.0    
  -14.0991    -2.01416  -34.2407     -12.085     -44.3115   -18.1274 
  -66.4673   -12.085    -46.3257     -10.0708    -46.3257   -20.1416 
  -22.1558     0.0      -12.085   …  -28.1982    -46.3257   -18.1274 
  -32.2266   -14.0991   -66.4673      -8.05664   -68.4814   -42.2974 
  -32.2266    20.1416   -14.0991      -8.05664   -30.2124   -14.0991 
    ⋮                             ⋱            

In [16]:
for a in DatosPrueba
    print(a)
end
#Okey, ya viste que trae adentro el HDF5. Ta chingon

HDF5 group: /3BData (file: /media/bodega/050815-hdf5/050815_1R0.brw)HDF5 group: /3BRecInfo (file: /media/bodega/050815-hdf5/050815_1R0.brw)HDF5 group: /3BUserInfo (file: /media/bodega/050815-hdf5/050815_1R0.brw)

In [24]:
ApuntaDatos=DatosPrueba["/3BData/Raw"]

HDF5 dataset: /3BData/Raw (file: /media/bodega/050815-hdf5/050815_1R0.brw)

In [25]:
Datos=read(ApuntaDatos);

In [31]:
size(Datos)

(4096,210624)

In [32]:
A=reshape(Datos, 64,64,210624);

In [34]:
factores=DatosPrueba["/3BRecInfo/3BRecVars"]

HDF5 group: /3BRecInfo/3BRecVars (file: /media/bodega/050815-hdf5/050815_1R0.brw)

In [35]:
facts=read(factores)

Dict{Union(UTF8String,ASCIIString),Any} with 6 entries:
  "NRecFrames"      => [210624]
  "SignalInversion" => [-1.0]
  "MinVolt"         => [-4125.0]
  "BitDepth"        => Uint8[12]
  "SamplingRate"    => [7020.800706028248]
  "MaxVolt"         => [4125.0]

In [38]:
2^facts["BitDepth"][1]

4096

In [41]:
FactorConversion=(facts["MaxVolt"][1]-facts["MinVolt"][1])/(2^facts["BitDepth"][1])*facts["SignalInversion"][1]

-2.01416015625

In [42]:
Offset=facts["SignalInversion"][1]*facts["MinVolt"][1]

4125.0

In [47]:
function tuabuela(x::Real)
    x+x
    
end

tuabuela (generic function with 2 methods)

In [49]:
?HDF5.H5D_CONTIGUOUS

1 is of type


INFO: Loading help data...


DataType   : Int64
  supertype: Signed
